### ISSUE TITLE
SDK 13.0: withSDKToken() builder results in nil OnfidoConfig 

### ISSUE THREAD

**Issue by edward-soetiono-asto** [onfido/onfido-ios-sdk#108]
### What was the expected behaviour?

`OnfidoConfig.builder().withSDKToken(..).build()` returns a **non-nil** `OnfidoConfig` object

### What happened instead?

`OnfidoConfig.builder().withSDKToken(..).build()` returns a **nil** `OnfidoConfig` object

### Version info:

- Cocoapods (if applicable): n/a
- Onfido SDK (Debug/Release): Release 13.0
- iOS: 12.4
- Xcode: 10.3
- Device/Simulator: 12.4
- Device/Simulator language: iPhone XS

### Integration configuration:

`withSDKToken()`
```
let onfidoConfig = try? OnfidoConfig.builder()
			.withSDKToken(<onfidoKEY>)
			.withApplicantId(applicantId)
			.withDocumentStep(ofType: documentType, andCountryCode: countryCode)
			.withFaceStep(ofVariant: .video(withConfiguration: nil))
			.build()
```

`withToken()`
```
let onfidoConfig = try? OnfidoConfig.builder()
			.withToken(<onfidoKEY>)
			.withApplicantId(applicantId)
			.withDocumentStep(ofType: documentType, andCountryCode: countryCode)
			.withFaceStep(ofVariant: .video(withConfiguration: nil))
			.build()
```
### Steps to reproduce:

using the new `withSDKToken()` results in **nil** `OnfidoConfig` (Wrong result)
using the deprecated `withToken()` results in non-nil `OnfidoConfig`  (Correct result)

**Comment by ramprasad-parajuli** [comment]
Hi @edward-soetiono-asto Thank you for flagging the issue. We will look into the issue and reach out to you as soon as possible.

**Comment by keremgund** [comment]
Hi @edward-soetiono-asto,
The problem is you're calling both .withSDKToken(<onfidoKEY>) and .withApplicantId(applicantId)
If you're using SDK token, you shouldn't pass applicantId to the config object as SDK token itself already bound to applicantId.

Just hint for the future to spot the reason of these kind of errors: Perform your builder operation inside try catch block and print error description inside catch, you should see clear error message.

Please let us know if you need further assistance.

Thanks,
Kerem

**Comment by edward-soetiono-asto** [comment]
got it, thank you!
