### ISSUE TITLE
Custom localisation using own translated files 

### ISSUE THREAD

**Issue by aurimas535** [onfido/onfido-ios-sdk#110]
I'm trying to integrate onfido with RN. For that I'm using this wrapper library https://github.com/MCROEngineering/react-native-onfido-sdk by default it doesn't support localisation so I added couple of lines extra code to do the job:
```
    if (variantConfigError != NULL) {
        return errorCallback(variantConfigError);
    } else {
      if (localeString != NULL) {
          [configBuilder withCustomLocalizationWithTableName:@"MY_STRING"];
      }
    }
```
The thing is that I don't know how to format localisation file name `MY_STRING` correctly to make it work. Any way to do that without localising files? Any assistance would help a lot since I'm not very familiar with Objective-C.

**Comment by anuragajwani** [comment]
@aurimas535 the code above will look for a file called `MY_STRING.strings` file in your app bundle.

Sample file with all the strings: https://github.com/onfido/onfido-ios-sdk/blob/master/Localizable.strings

Since version [11.0.0](https://github.com/onfido/onfido-ios-sdk/blob/master/CHANGELOG.md#1100---2019-04-01) you can use non-localised strings files too.

Hope that answers your question,
Anurag

**Comment by anuragajwani** [comment]
Let me know if this fixes your problem.

**Comment by anuragajwani** [comment]
@aurimas535 you have to use specify "Resources" as the resource bundle. 

```
NSBundle *resourceBundle = .... // load resources folder as a bundle
[configBuilder withCustomLocalizationWithTableName:@"MY_STRING" in: resourceBundle];
```

**Comment by anuragajwani** [comment]
closing issue now that its stale
