### ISSUE TITLE
Document flow customization

### ISSUE THREAD

**Issue by clapslock** [onfido/onfido-ios-sdk#166]
Is there a way to provide a custom UI for document type selection (Passport, Driver's license, Identity card, ...) and then start the `DocumentStep` with Select issuing country screen? If that's not possible, then how can I get the list of currently supported countries for selected document type?

**Comment by andra-radu** [comment]
Hi @clapslock, 
You can definitely customise the document steps following the steps provided here: https://github.com/onfido/onfido-sdk-ui under document section and then initiate the sdk flow with a specified document.

**Comment by anuragajwani** [comment]
Hi @clapslock 

Are you looking to customise the document types that the SDK should capture?

Maybe this issue is related:
https://github.com/onfido/onfido-ios-sdk/issues/123

We also don't currently expose the document types and countries that are supported. Related issue:
https://github.com/onfido/onfido-ios-sdk/issues/63

Could you please confirm whether:
1. you are trying to specify the document types the SDK should capture
2. if not then trying to get the supported document types and countries so you can build your own document type and country selection

**Comment by clapslock** [comment]
Sorry for the late response. 
I just wanted to make sure I'm not missing anything. I guess I'll have to use POI type picker from your SDK. Thanks!
