### ISSUE TITLE
Bitcode/App thinning issue while releasing with Xcode 12

### ISSUE THREAD

**Issue by sree127** [onfido/onfido-ios-sdk#184]
### What was the expected behaviour?

Upload ipa to iTunes connect

### What happened instead?

Upload failed stating bitcode/app thinning issue

### Version info:

- Cocoapods (if applicable):1.9.3
- Onfido SDK (Debug/Release):18.3.0 (Release)
- iOS:14.0
- Xcode:12.0 (12A7209)
- Device/Simulator:
- Device/Simulator language:

### Export ipa using Xcode - Adhoc
![Screenshot 2020-09-25 at 08 48 44](https://user-images.githubusercontent.com/3157263/94236369-63aa8a00-ff0d-11ea-9e34-8c4a1580f613.png)

### Using fastlane
* Uploaded release build using fastlane ✅
* iTunes processing failed with the below error ❌

<img width="663" alt="Screenshot 2020-09-24 at 20 41 05" src="https://user-images.githubusercontent.com/3157263/94236612-d1ef4c80-ff0d-11ea-8ee9-53059b56055b.png">

This is currently blocking the release :( and would be nice to have a solution soon-ish :) Thanks

**Comment by andra-radu** [comment]
Hi @sree127,

Thank you for reaching out with the issue.

Could you please confirm if that you are not using special characters in the name of your app?

Also, I see that you have included 'Onfido' into a project using cocoapods. Could you please replace pod 'Onfido' with the following lines?

use_frameworks!
pod 'Onfido', '10.0.0', :configurations => ['Debug']
pod 'Onfido-Release', '10.0.0', :configurations => ['Release']

Please let us know how it goes.
Kind regards,

**Comment by sree127** [comment]
Thanks for the prompt response @andra-radu :) I will try and update here though one thing to note here is we embed pods as static frameworks and hence no `use_frameworks !` :)

**Comment by andra-radu** [comment]
I understand @sree127 

Just to confirm, are you using special characters in the name of your app?

**Comment by sree127** [comment]
Nop. We don't use any special characters in the name.

**Comment by andra-radu** [comment]
Thank you for your confirmation. I've raised this with our iOS SDK engineers and I will get back to you as soon as I will receive more information from them.

**Comment by sree127** [comment]
FYI: I tried adding `configurations => ['Release']` and the issue still persists. Got the same error again.

**Comment by andra-radu** [comment]
Thank you for trying to add configurations => ['Release']. I'm currently checking with our SDK engineering team and will get back to you as soon as I will receive an update from them.

**Comment by keremgund** [comment]
Hi @sree127 ,
I've just tested SampleApp (the one you can find in this repo) with integrating to `18.3.0` Onfido SDK through cocoapods (without using !use_frameworks) and got successful Appstore validation result can be seen below:

![Screenshot 2020-09-28 at 16 13 48](https://user-images.githubusercontent.com/49163858/94451022-d9c91e00-01a5-11eb-9dd6-8065185c0643.png)

So I don't know the reason of the error you got, the screenshot you shared doesn't contain any information that we can investigate.

If you really think that this issue is related with the Onfido SDK, then we need more detailed logs (you might get it after clicking Show Logs button on dialog) to be able to conduct further investigation.

Thanls,
Kerem

**Comment by sree127** [comment]
Yep. We also checked the same. This is not related to Onfido. Sorry for the false alarm :) 
Thanks for checking.
