### ISSUE TITLE
Broken passport scan screen on iOS 14/ Onfido SDK 18.6.0

### ISSUE THREAD

**Issue by iangmaia** [onfido/onfido-ios-sdk#186]
### What was the expected behaviour?

Normal passport capture screen should be shown

### What happened instead?

Passport capture screen is broken, no button or label is shown. Lot's of constraints breaking warnings are shown on the console.

### Version info:

- Onfido SDK (Debug/Release): 18.6.0
- iOS: 14.0
- Xcode: 12.0.1

The button / labels aren't shown for Passport scan, in **all** screen sizes. The console shows a lot of auto layout constrains breaking (this was already the case before, but now the actual layout is broken).
See screenshot:

![Simulator Screen Shot - iPod touch (7th generation) - 2020-10-02 at 13 56 24](https://user-images.githubusercontent.com/2152244/94921032-c1b01200-04b7-11eb-8527-707b21c1fe12.png)

**Comment by anuragajwani** [comment]
Hi @iangmaia 

As part of version 18.4.0 we have enabled passport auto capture. As with US DL auto capture the capture button appears after a certain period of time since the first time a document is defected within a frame. 

We will look into the auto layout constraints issue (warnings logged in console). Though the layout on the image is as expected. We will introduce a fix so that on simulators you don’t see autocapture.

Sorry for the inconvenience caused,
Anurag

**Comment by iangmaia** [comment]
Ah, got it! Thanks for the info, I hadn't realise that yet.
Though the copy still mentions the button, but I guess we need to update it on our side.

**Comment by anuragajwani** [comment]
@iangmaia we are close to completing the release for 18.8.0 tomorrow. As part of 18.8.0 we are including higher degree of copy customisation for the integrator. We have separated the key for manual and auto capture for passport. 

Thus you should now be able to keep "Make sure the whole photo page appears in the frame, then tap button" for manual and tweak the autocapture copy.

Also given that this ticket encases three points:
- broken screen (not broken this is by design)
- copy change (also by design but enhanced SDK functionality to allow you to tweak auto copy)
- constraints

Could you kindly open another ticket specifically for the constraints issue please?

I'll update you when we complete 18.8.0 release.

Thanks,
Anurag

**Comment by anuragajwani** [comment]
@iangmaia we have now completed release of [18.8.0](https://github.com/onfido/onfido-ios-sdk/blob/master/CHANGELOG.md#1880---2020-10-13)

**Comment by keremgund** [comment]
Closing the issue due to lack of response.
Please open new one if you need further assistance.

Thanks,
Kerem
