### ISSUE TITLE
CoreNFC framework flow missing. App Store rejection due to NFC.

### ISSUE THREAD

**Issue by ignasvalotka** [onfido/onfido-ios-sdk#195]
### What was the expected behaviour?
CoreNFC flow to start when verifying a document.

We submitted our app for Apple review and it got rejected because the use of NFC tagging was unclear. Quote from review:
"Specifically, please provide a demo video, demonstrating the NFC tag integration, in the app."

### What happened instead?

Then we noticed that we were unable to start the NFC flow from the SDK (after following the steps to integrate it). Thus we cannot comply with Apple's request for the video. 

If we cannot start the flow is there a way to turn off the NFC tagging from the framework? (the app got rejected without the `withPassportNFCReadBetaFeatureEnabled()` step) 

### Version info:

- Onfido SDK (Debug/Release): Release 18.8.0
- iOS: 14.1
- Xcode: 12.1
- Device/Simulator: iPhone 7 Plus
- Device/Simulator language: English

### Integration configuration:

` let config = try OnfidoConfig.builder()
                    .withSDKToken(response.sessionToken)
                    .withWelcomeStep()
                    .withDocumentStep(ofType: documentType)
                    .withPassportNFCReadBetaFeatureEnabled()
                    .withFaceStep(ofVariant: .video(withConfiguration: nil))
                    .build()`

**Comment by anuragajwani** [comment]
@ignasvalotka 

The integration configuration shows `withPassportNFCReadBetaFeatureEnabled()` however you state that the app got rejected without calling that function.

We're sorry to hear that Apple is rejecting your app due to the use of NFC. Why aren't you able to start the NFC flow? To view the NFC flow enable `.withPassportNFCReadBetaFeatureEnabled()` in your configuration and capture auto capture a passport. If the autocapture is able to successfully extract the data from the passport photo page then you'll the NFC flow.

We are looking into sharing a video with you. Would that help?

**Comment by ignasvalotka** [comment]
Thank you for such a quick response. 
A video would help greatly!

My email ignas.valotka@trafi.com

**Comment by anuragajwani** [comment]
@ignasvalotka here is the video of the NFC flow. During the NFC flow we are extracting the passport information captured during the passport document capture step.

Let me know if this helps.
[onfido-14-beta-log.txt](https://github.com/onfido/onfido-ios-sdk/files/5494313/onfido-14-beta-log.txt)

**Comment by ignasvalotka** [comment]
Apple has approved the build. Thank you!
