### ISSUE TITLE
Unable to use cocoapods static library because of referencing Alamofire.framework

### ISSUE THREAD

**Issue by ilyavelilyaev** [onfido/onfido-ios-sdk#37]
I am trying to use new Cocoapods 1.5.0 feature supporting static libraries in Swift to avoid linking a lot of libraries on application start and reduce Launch Time.

Onfido causes problems because of referencing Alamofire.framework
```
dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: ~/Library/Developer/CoreSimulator/Devices/0ECD1951-8361-4A6B-BC5A-B61261444BAA/data/Containers/Bundle/Application/15791FB5-D29D-49E3-8532-2E522C4C351A/Onfido-Test.app/Frameworks/Onfido.framework/Onfido
  Reason: image not found
```

Here is example project that cannot be run. Using cocoapods 1.5.0

[Onfido-Test 2.zip](https://github.com/onfido/onfido-ios-sdk/files/2048783/Onfido-Test.2.zip)

**Comment by ilyavelilyaev** [comment]
@anuragajwani by the way, Why do you need this much dependencies in your Framework?

**Comment by anuragajwani** [comment]
@ilyavelilyaev we went down the dependency route when we had to bootstrap the project but we are now underway into removing them

**Comment by ilyavelilyaev** [comment]
@anuragajwani I think you've added ZSW* things just recently

**Comment by rfreitas** [comment]
Hi @ilyavelilyaev,

The ZSW is used on our privacy screen (not yet released) to allow us to have multiple translations on a paragraph which has both text and urls. At the moment the privacy screen is under review, which might lead to the removal of these dependencies down the line.

Also, the the ZSW is not as common of a dependency as Alamofire, which is why we are focused on removing that first, since it has a higher chance of creating conflicts with the host app.

**Comment by ilyavelilyaev** [comment]
Looking forward to see less dependencies in future, as we are trying to get rid of them as well to reduce launch time because of dynamic linking. 
Also would be great if Onfido could be distributed as a static library as well
Good luck! 😃

**Comment by rfreitas** [comment]
All things we are looking forward to see too! Thanks :)
