### ISSUE TITLE
Carthage support ?

### ISSUE THREAD

**Issue by mmdumi** [onfido/onfido-ios-sdk#44]
Hi guys, could you please add carthage support for onfido ?

**Comment by mmdumi** [comment]
For now I ended up compiling onfido + dependencies separately from cocoapods and link everything together with lipo -create and use the resulting frameworks with carthage copy-frameworks script.
It would be great if you could get rid of the dependencies and provide and compiled version of the onfido sdk with carthage. For many of us cocoapods it's too much of a mess to integrate into our projects.

**Comment by PorridgeBear** [comment]
+1

**Comment by anuragajwani** [comment]
@mmdumi @PorridgeBear we have just released iOS SDK version 10.0.0 which is dependency free. For now you can directly download it.

- debug: https://s3-eu-west-1.amazonaws.com/onfido-sdks/ios/Onfido-Debug-v10.0.0.zip
- release: https://s3-eu-west-1.amazonaws.com/onfido-sdks/ios/Onfido-Release-v10.0.0.zip

-

**Comment by omerduzyol** [comment]
Hey @anuragajwani 
I've tried to use `v10.0.0` both directly by downloading and using Pods but I'm getting this runtime error on both cases.

```
dyld: Symbol not found: _$SBOWV
  Referenced from: /private/var/containers/Bundle/Application/9CB78C82-BAA8-4C05-96D7-B65313787244/Test.app/Frameworks/Onfido.framework/Onfido
  Expected in: /private/var/containers/Bundle/Application/9CB78C82-BAA8-4C05-96D7-B65313787244/Test.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/9CB78C82-BAA8-4C05-96D7-B65313787244/Test.app/Frameworks/Onfido.framework/Onfido
```

**Comment by anuragajwani** [comment]
Is this related to the use of Carthage? If its not please file a new issue and fill in the form so it can we fix your problem with all relevant information required to do so.

**Comment by omerduzyol** [comment]
Well, the root cause was incompatibility with Carthage. I was trying to aligned my current Carthage config with Onfido v10.0.0 then realized something wrong with fat library. 

After, I wanted to make sure if the problem also applies with pods then tried with pods using an empty project and got the same problem with the latest version. I can create another issue if you need but this still linked with Carthage.

**Comment by anuragajwani** [comment]
I created a project from scratch using Xcode 10 and cocoapods 1.5.3 and the integration worked.

### Version info:

- Cocoapods (if applicable): 1.5.3
- Onfido SDK (Debug/Release): Debug 10.0.0
- iOS: 12.0
- Xcode: 10.0.0
- Device/Simulator: iPhone SE
- Device/Simulator language: English

**Comment by iangmaia** [comment]
+1 for this.

**Comment by anuragajwani** [comment]
@iangmaia Thanks for letting us know, we appreciate your feedback. Carthage support is being considered. I will update this issue as we receive more news on this front.

Anurag

**Comment by iangmaia** [comment]
Another point related to this: since Onfido provides the binary releases, I'm using them with Carthage as a binary library using the `binary` option in the Cartfile. This is good enough if someone wants to use Onfido with Carthage.

You just need to provide Carthage with a JSON file (which can be hosted remotely) such as:
`{
  "10.4.0": "https://github.com/onfido/onfido-ios-sdk/releases/download/10.4.0/Onfido-Debug-v10.4.0.zip",
  "10.3.0": "https://github.com/onfido/onfido-ios-sdk/releases/download/10.3.0/Onfido-Debug-v10.3.0.zip"
}`

This is better described [here](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md).

The problem: the Release version of the framework doesn't seem to have everything exported to Swift. Classes such as `OnfidoConfig` don't seem to be available, only in the Debug version. I've double checked it by adding it manually as well. Can you guys please check this?

Thanks!

**Comment by anuragajwani** [comment]
We don't recommend to use `Onfido-Debug` for releasing. `Onfido-Release` is built using another build profile and does not include the simulators slices in the binary. Which is why you may find that OnfidoConfig is not included because your trying to use `Onfido-Release` on a simulator. However if you use `Onfido-Release` in a device it should work.

This separation was done initially to cater to the App Store rejecting any framework with simulator slices. We will work in the future to reduce `Onfido-Debug` and `Onfido-Release` to a single framework. I believe that should help Carthage integration. Please correct me if I am wrong.

**Comment by iangmaia** [comment]
Got it! Makes sense.

Having one single framework would help, I believe. For now I'll try to do some build workaround to switch between debug/release.

Thanks!

**Comment by anuragajwani** [comment]
@iangmaia a possible solution that can work for you is to have a folder with the location of debug and release and the currently selected SDK i.e. `{PROJECT_ROOT}/OnfidoSDK/[debug|release|current]` (maybe git ignore these from git) then have a build script before the sources step such as the following:

```
if [[ "$ACTION" == "install" ]]; then
cp -r "${SRCROOT}/onfido-sdk/release/Onfido.framework" "${SRCROOT}/onfido-sdk/current/"
else
cp -r "${SRCROOT}/onfido-sdk/debug/Onfido.framework" "${SRCROOT}/onfido-sdk/current/"
fi
```

make sure your embedded binaries reference `{PROJECT_ROOT}/OnfidoSDK/current`.

This should select the release SDK only when archiving the app. 

Hope this helps,
Anurag

**Comment by danny-bravo-og** [comment]
+1

**Comment by anuragajwani** [comment]
Hey all, a little update on our side: we started testing our release process using a single framework. We are aiming in the next release or the one after that to have it available to you.

**Comment by anuragajwani** [comment]
Hi all,

We have release iOS SDK 11.1.0 which includes support for a single framework. Please use the debug framework. We still support both universal and device only framework for the time being. We are still working to support Carthage, however my understanding is that a single framework would allow some ease on integration for those using Carthage.

Please let me know if you encounter any issues.

Anurag

**Comment by keremgund** [comment]
Closing this issue due to lack of response, if you think there is still an issue about it, you can open new ticket.

Thanks,
Kerem
