### ISSUE TITLE
Swift Compiler Error Group

### ISSUE THREAD

**Issue by yoginair** [onfido/onfido-ios-sdk#67]
Stuck in this two errors while building the build for IOS react-native.
```
ios/OnfidoSDK.swift:26:29: Use of unresolved identifier 'OnfidoConfig'

ios/OnfidoSDK.swift:33:22: Use of unresolved identifier 'OnfidoFlow'
```

**Comment by anuragajwani** [comment]
which framework are you using Onfido or Onfido-Release?

**Comment by yoginair** [comment]
Onfido-Debug-v10.1.0 (1).zip

**Comment by yoginair** [comment]
I have commented  use_frameworks!  in my podfile and added Onfido-Debug manually.

**Comment by ncuthbert** [comment]
I'm having the same issue in my React Native project. How was this resolved? 

I'm having build issues on CircleCI, so I am adding the frameworks directly to the project (instead of through pods) in hopes that it will correct the issue, but now when I try building to simulator I'm getting these errors.

**Onfido version**: 10.5.0
